version: '3'
services:
  app:
    container_name: auth_api
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:5000"
    volumes:
      - ./src:/app/src
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-authapp-network
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27018:27017"
    networks:
      - node-authapp-network
networks:
  node-authapp-network:
    driver: bridge
    